"""
:Status: $Id: //prod/main/_is/shared/python/avc/traffic_corpus/constants.py#2 $
:Author: $Author: usarfraz $
"""

APP_KW = 'app'
BEHAVIOR_KW = 'behavior'
CHUNKD_KW = 'chunked'
CODE_KW = 'code'
CONN_KW = 'connections'
CONN_DATA_KW = 'connection_data'
CONN_DICT_KW = 'conn_dict'
CONTENT_LEN_KW = 'content-length'
CONTENT_TYPE_KW = 'content-type'
DATA_OFFSET_KW = 'data_offset'
DEST_IP_KW = 'dest_ip'
DEST_PORT_KW = 'dest_port'
END_TS_KW = 'end_ts'
HDR_LEN_KW = 'header_len'
HDRS_KW = 'headers'
HTTP_CODE_KW = 'http_code'
HTTP_METH_KW = 'http_method'
HTTP_VER_KW = 'http_version'
METH_KW = 'method'
NUM_PACKETS_KW = 'number_packets'
PAYLD_KW = 'payload'
PATH_KW = 'path'
PLAIN_TXT_KW = 'plain-text'
PORT_KW = 'port'
PROTO_KW = 'protocol'
RAW_CONTENT_KW = 'raw_content'
RAW_KW = 'raw'
REASON_KW = 'reason'
REQUEST_KW = 'request'
RESPONSE_KW = 'response'
RNDRD_CONTENT_KW = 'rendered_content'
RNDRD_KW = 'rendered'
SEQ_NUM_KW = 'sequence_number'
SIZE_KW = 'size'
SRC_IP_KW = 'src_ip'
SRC_PORT_KW = 'src_port'
START_TS_KW = 'start_ts'
TAR_KW = 'tar'
TRNSFR_ENCDNG_KW = 'transfer-encoding'
TOT_LEN_KW = 'total_len'
TRANSACT_KW = 'transactions'
TRANSACT_DATA_KW = 'transaction_data'
TRANSACT_TYPE_KW = 'transaction_type'
VER_KW = 'version'
WORK_FILE_PATH_KW = 'working_file_path'

HTTP_METH_DICT = ['GET', 'HEAD', 'DELETE', 'OPTIONS', 'TRACE', 'CONNECT']
REQ_METH_DICT = ['POST', 'PUT']
